openapi: "3.0.0"
info:
  version: 1.0.0
  title: Foo API
  description: Foo API
servers:
  - url: http://localhost:8080
paths:
  /foo:
    get:
      tags:
        - Foo
      description: Returns all Foo items
      operationId: getAllFoos
      responses:
        '200':
          description: foo response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Foo'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      tags:
        - Foo
      description: Creates a new foo item
      operationId: addFoo
      requestBody:
        description: Foo item to add
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Foo'
      responses:
        '201':
          description: transaction response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Foo'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /foo/{id}:
    delete:
      tags:
        - Foo
      description: deletes a single Foo item based on the ID supplied
      operationId: deleteFooById
      parameters:
        - name: id
          in: path
          description: ID of the Foo item to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: transaction deleted
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Foo:
      type: object
      required:
        - bar
      properties:
        id:
          type: integer
          format: int64
        bar:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string